### ISSUE TITLE
Cashier version requirement causes failed installation

### ISSUE THREAD

**Issue by eorenstein1** [keithbrink/affiliates-spark#1]
Using Laravel 5.8 and Spark 8, I'm unable to install this package because it's requiring "laravel/cashier": "~7.0", but the current version is ~9.3.

Error message below:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/cashier[7.0.x-dev, v9.3.1].
    - Can only install one of: laravel/cashier[v9.3.1, 7.0.x-dev].
    - Can only install one of: laravel/cashier[7.0.x-dev, v9.3.1].
    - keithbrink/affiliates-spark 0.1.9 requires laravel/cashier ~7.0 -> satisfiable by laravel/cashier[7.0.x-dev].
    - Installation request for keithbrink/affiliates-spark ^0.1.9 -> satisfiable by keithbrink/affiliates-spark[0.1.9].
    - Installation request for laravel/cashier (locked at v9.3.1, required as ~9.3) -> satisfiable by laravel/cashier[v9.3.1].

**Comment by keithbrink** [comment]
Thanks for reporting. This has been resolved in version 0.2.1.
