### ISSUE TITLE
Views and spark functions not doing anything in laravel 6.

### ISSUE THREAD

**Issue by AlexFoster009** [keithbrink/affiliates-spark#11]
Hello there, i followed your directions to the letter but no affiliate_id is being created when a user registers and the views associated with the package are not showing up in the user dashboard. In fact the only notable addition i see is the extra column for affiliate_id in the database. Is the package not compatible with laravel 6?

**Comment by ricoxor** [comment]
I changed many thing for Laravel 6 compatibility.
There were some things I had to do less cleanly because I couldn't adapt.
I'll try to make a pull request when I get it right.

**Comment by keithbrink** [comment]
I'll attempt a fresh install sometime in the next couple weeks.

**Comment by greghunt** [comment]
This PR got it working for me: https://github.com/keithbrink/affiliates-spark/pull/12

**Comment by keithbrink** [comment]
Thanks @greghunt your changes were added as well as a lot more fixes to make the library compatible with Laravel 6 / Cashier 10.
