### ISSUE TITLE
Error on Install

### ISSUE THREAD

**Issue by savage-eagle** [keithbrink/affiliates-spark#16]
Hi, adding the package to the project is returning: `Call to undefined method Spark\SparkManager::createUsersWith()` on Facade.

Regards,
savage.

**Comment by keithbrink** [comment]
Are you on the new version of Spark? This is for the old version.

**Comment by savage-eagle** [comment]
Oh sorry, I didn't readed about the versions previously. Any wip to update?

**Comment by keithbrink** [comment]
Afraid not.
