### ISSUE TITLE
replace spark settings with affiliate settings to remove unwanted links

### ISSUE THREAD

**Issue by jayenne** [keithbrink/affiliates-spark#4]
Whilst logged in as an affiliate, an affiliate may wish to edit thier password and name/avatar they have no need to adit the API or Teams menu. If it's not possible to hide these from within the package code, then would you include examples within your docs showing exactly how  hide them in the spark templates.

**Comment by keithbrink** [comment]
I think the easiest think here would be to edit `resources/views/vendor/spark/nav/user.blade.php` and add a quick check: `$user->isAffiliate();`
