### ISSUE TITLE
Cashier 10 errors

### ISSUE THREAD

**Issue by ricoxor** [keithbrink/affiliates-spark#9]
Hello,
First of all, thank you for this wonderful package!
I would just like to inform you that with the new version of the Cashier, some functions are no longer available such as: usesCurrencySymbol().
I'll try to make a PR to fix that.

**Comment by keithbrink** [comment]
Thanks for the FYI, a PR would be much appreciated if you get to it.

**Comment by keithbrink** [comment]
Cashier 10 is now supported in version 1.0.0+
